### ISSUE TITLE
Holiday Wishes...

### ISSUE THREAD

**Issue by ibuprophen1** [yashdsaraf/bb-bot#2]
I just wanted to wish @yashdsaraf Family and Friends the Best Wishes, Happy Holidays and a Happy New Year!!! 

I hope this year ends even more Uplifting and Promising as the last (bumpy) year has ended with!! 

Take care My Friend. 

~Ibuprophen

**Comment by yashdsaraf** [comment]
Hey, thanks @ibuprophen1 and wish you and your family the same. Yeah the past 3-4 months have been bumpy :P, that'll change soon, hopefully :D.
